codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 95%
        threshold: 2%
        if_ci_failed: error
    patch:
      default:
        target: 90%
        threshold: 5%

comment:
  layout: "reach,diff,flags,tree,files"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "tests/"
  - "**/__pycache__/"
  - "**/*.pyc"
  - "htmlcov/"
  - ".pytest_cache/"
  - "**/__init__.py"
  - "migration*.py"
  - "criar_tabelas*.py"
  - "extrair_schema.py"
  - "limpar_*.py"
  - "popular_dados_teste.py"
  - "testar_*.py"
  - "verificar_*.py"
